### ISSUE TITLE
All IOutput implementations are always used

### ISSUE THREAD

**Issue by mgroves** [hmol/LinkCrawler#10]
Unless I'm misunderstanding something, it seems like all IOutput implementations are always used for each 'error' response.

One thing that might be nice is that currently your program will try to output to ALL implementation of IOutput. It might be better to all that to be configurable (e.g. in app config).

Something like:
<add key="UseOutputs" value="SlackOutput,CsvOutput,ConsoleOutput" />

So, if you keep adding output options (as in issue #6), you don't have to keep writing to all of them. Does that sound like a useful feature?

**Comment by hmol** [comment]
In `App.config` I have a setting `OnlyReportBrokenLinksToOutput`, if true then only error-links will be outputted, if false all links will be outputted.
Outputting to several different "outputs" at the same time is confusing and not necessary. So it sounds very useful to make this configurable :bowtie:.

**Comment by mgroves** [comment]
Looks like @Wizhi beat me to it!

I'll wait for this to get merged in before I finish #6
