### ISSUE TITLE
Improve summary to include breakdown of link counts by status

### ISSUE THREAD

**Issue by tdwright** [hmol/LinkCrawler#22]
Now that we've got the option to output the elapsed time at the end of processing (PR #21), it might be good to offer a summary table too. This could list the different statuses alongside the counts of links for each. E.g.:

| Status | Links |
| --- | --- |
| 200 | 113 |
| 301 | 12 |
| 302 | 6 |
| 404 | 3 |
| 418 | 1 |

To achieve this we could turn the two lists of strings into a list of objects that contain the link URL, a bool for whether or not we've processed the response yet, and a field for the status code.

**Proposed subtasks:**
- [x] Replace the two string lists with a list of instances of a new class
- [x] Include a summary table when outputting the time elapsed

Thoughts very welcome.

**Comment by hmol** [comment]
Sounds like you've got it figured out. I think this sounds great! 👍

**Comment by leglock** [comment]
Should this issue be closed? Looks like @hmol addressed it in #23.

**Comment by tdwright-itg** [comment]
Yep, this got merged in. Don't think I can close it, but happy for it to be closed.

**Comment by hmol** [comment]
Sorry! Closed it now! I will sometimes have little time to follow up on this project. If some of you would like I could add you to administrator?

**Comment by tdwright** [comment]
Hi @hmol - I'm happy to help out as and when I can.

**Comment by hmol** [comment]
@tdwright thanks! you are now added as contributor :)
