### ISSUE TITLE
Pass url as a command line argument

### ISSUE THREAD

**Issue by melkor54248** [hmol/LinkCrawler#29]
How about being able to run the app like this: LinkCrawler www.mycoolsite.com as an alternative option?

**Comment by ibzib** [comment]
I agree, this would be convenient

**Comment by tdwright** [comment]
Sounds good to me. If you'd like to give it a go, please feel free to fork and then raise a pull request when you're done.

**Comment by melkor54248** [comment]
I already did 🙂

**Comment by tdwright** [comment]
Whoop! So you did.

Looked good to me, so I merged it in.

Thanks!
Tom

**Comment by melkor54248** [comment]
🙂
